# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a2b7c37e78add407b504b000edb6dc170da33cc02eafc27fc3afbcd53fb857d457e0f410b7c4469542b35ceae8f5920f8a3c9fcd6db28db93401c7ddec0a8ba

test:
  secret_key_base: 3fb4e6352aa888a182728785b6ca54969d5cfca246b7ecf7ec767b9b5627bb3edc36d71d092e54f91a7e99a0b72efdf355f8d68d61fb2d9500d944a10e680dfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
